### ISSUE TITLE
FATAL: Errno::ECONNREFUSED: ruby_block[create-admin-user] (riak-cs-create-admin-user::default line 8) had an error: Errno::ECONNREFUSED: Connection refused - connect(2)

### ISSUE THREAD

**Issue by dn** [basho-labs/vagrant-riak-cs-cluster#10]
I only cloned and runed 
   RIAK_CS_CREATE_ADMIN_USER=1 vagrant up

any tips?

**Comment by hectcastro** [comment]
Please see the answer I provided in https://github.com/basho/vagrant-riak-cs-cluster/issues/9#issuecomment-16335064 – I believe you're facing the same issue.

Sorry for the confusion.

**Comment by hectcastro** [comment]
`1.3.1` support for Riak CS has been merged into the Riak cookbook. The workaround should no longer be needed.
