### ISSUE TITLE
Vagrant 1.0.7, which is mentioned as required in the README, doesnt currently work with this vagrantfile.

### ISSUE THREAD

**Issue by simonvc** [basho-labs/vagrant-riak-cs-cluster#11]
RIAK_CS_CREATE_ADMIN_USER=1 vagrant up

/Users/simonvc/Desktop/TRaining/vagrant-riak-cs-cluster/Vagrantfile:20:in `<top (required)>': undefined method`configure' for Vagrant:Module (NoMethodError)
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.7/lib/vagrant/config/loader.rb:115:in `load'
    from /Applications/Vagrant/embedded/gems/gems/vagrant-1.0.7/lib/vagrant/config/loader.rb:115:in`block in procs_for_source'

**Comment by hectcastro** [comment]
Ah, this is a mistake in the README. Initially we had to require that version due to a Berkshelf compatibility issue with Vagrant 1.1+.

**Comment by hectcastro** [comment]
Resolved by https://github.com/basho/vagrant-riak-cs-cluster/pull/12.
