### ISSUE TITLE
Failed to download 'riak_cs' from github: 'basho/riak-cs-chef-cookbook' over protocol: 'ssh'

### ISSUE THREAD

**Issue by dn** [basho-labs/vagrant-riak-cs-cluster#2]
https://github.com/hectcastro/vagrant-riak-cs-cluster/blob/master/Berksfile#L11

Failed to download 'riak_cs' from github: 'basho/riak-cs-chef-cookbook' over protocol: 'ssh'
An error occured during Git execution:
    ERROR: Repository not found.
    fatal: The remote end hung up unexpectedly

**Comment by hectcastro** [comment]
In the process of coordinating the private to public flip of that repository – please standby.

**Comment by dn** [comment]
works now, thank you!
