### ISSUE TITLE
changing the proxy port

### ISSUE THREAD

**Issue by vogxn** [basho-labs/vagrant-riak-cs-cluster#24]
I have my server running on 8080 and having the proxy_port 8080 set for s3cmd to interact with the riak cluster fails my deployment.

How can I alter the port in the Vagrant file?

**Comment by vogxn** [comment]
I tried 8098 as well and get a connection refused

``` bash
vagrant@riak1:~$ s3cmd -c ~/.s3cfgfasttrack ls
WARNING: Retrying failed request: / ([Errno 111] Connection refused)
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: / ([Errno 111] Connection refused)
WARNING: Waiting 6 sec...
^CSee ya!
```

**Comment by hectcastro** [comment]
Hey @vogxn,

We setup the project so that port `8080` within the VM guest would be forwarded to the VM host. From the host, you should be able to connect to Riak CS via proxy host `localhost` and proxy port `8080`.

It looks like you're trying to connect to Riak CS from within the VM. In this case you need to use the IP address of `eth0` as proxy host for `s3cmd`.

Please let me know if that worked out for you.

**Comment by vogxn** [comment]
@hectcastro I've got a couple of other boxes running on vboxnet0 in VirtualBox. So the vagrant up put the riak cluster on vboxnet1 where it has the ip `33.33.33.1`. `localhost` gives me `Connection Refused` but `33.33.33.1` as `proxy_host` works for me from outside the VM.

And as you pointed out from within the VM `eth0` which is on VirtualBox NAT works fine.

I found the following lines in the Vagrant Port forward file from the vmguest -> host 

``` ruby
      if index == 1
        config.vm.network :forwarded_port, guest: 8000, host: 8000
        config.vm.network :forwarded_port, guest: 8080, host: 8080
        config.vm.network :forwarded_port, guest: 8085, host: 8085
        config.vm.network :forwarded_port, guest: 8087, host: 8087
        config.vm.network :forwarded_port, guest: 8098, host: 8098
       end
```

 I expect that if I change the port for 8080->8080 to 8080->9090 may be it should work with my other webserver that runs on 8080. That would work?

**Comment by hectcastro** [comment]
I believe so. Just in case it doesn't, further documentation on the `:forwarded_port` directive can be found here [0].

[0] http://docs.vagrantup.com/v2/networking/forwarded_ports.html

**Comment by vogxn** [comment]
It works! Changed to `proxy_port=8081` and can access the buckets now

**Comment by hectcastro** [comment]
Nice! Let us know how it goes.
