### ISSUE TITLE
Missing contents of the cookbooks directory

### ISSUE THREAD

**Issue by imsickofmaps** [basho-labs/vagrant-riak-cs-cluster#7]
If I browse the master branch of this repo into the `cookbooks` folder it appears to be empty. I want to review the cookbooks, how can I do this?

**Comment by cheeseplus** [comment]
The cookbooks are pulled in by the Berksfile and exist as their own separate basho repositories:

https://github.com/basho/riak-chef-cookbook
https://github.com/basho/riak-cs-chef-cookbook

**Comment by imsickofmaps** [comment]
Thanks...
